### ISSUE TITLE
How to map multiple beans?

### ISSUE THREAD

**Issue by smiklosovic** [xebia-france/selma#100]
Hi

I have two classes and one dto. I want to map both classes to that dto. How to do that? I know how to map one class to dto but I need to do kind of "aggregation" of classes into one dto object. Is that possible?

**Comment by slemesle** [comment]
Hi, 


This is not supported by Selma for now.  But you can define one mapping method per class to map on the targetted DTO.  

We can for sure implement this kind of aggregation, but that won't be available soon.

**Comment by smiklosovic** [comment]
i first did mapping from the first source to the destination and after that second source updates the destination. With setting ignore missing flag to ALL because it would tell that source does not have target fields otherwise.

**Comment by CityIntense** [comment]
I have a class FooIn and an id that want to map to a class Out.

public class Out {

    private FooOut Foo;
	
	private Long id;
	
	}
	
I'd like to use a mapper as :

Out asOut(FooIn Foo, Long id);

Doing so, I get this error :
setter for field id from destination bean Out has no getter in one of source beans !
I can use a class to wrap my id to make my mapper work, but it would be great if I could only use the Long id.
