### ISSUE TITLE
Provides a way to generate inverse mapping automatically

### ISSUE THREAD

**Issue by softdays** [xebia-france/selma#103]
At the moment (v0.14) Selma provides support for inverse mapping in the following way:
1°- use class level mapping
2°- explicitly declare the inverse signature

Here is a example from Selma documentation:
```java
@Mapper
public interface PersonMapper {
    PersonDto asPersonDTO(Person source);
    Person asPerson(PersonDTO source);
}
```
I think it would be nice that Selma automatically generates the inverse mapping. It could be property driven and (IMHO) activated by default:
```java
@Mapper
public interface PersonMapper {
    @Maps(inverse=true)    
    PersonDto asPersonDTO(Person source);
}
```

**Comment by slemesle** [comment]
Hi,

the main issue I see with it is that, you'll need to refer to generated type for inverse mapping. 
Since the reverse method is not declared in the PersonMapper interface, you won't be able to refer to it in your code. 

If you have an idea for doing it correctly, we can work on it.

**Comment by softdays** [comment]
You're right. I 've been blinded by my precipitation. I don't see any way to deal with this issue.
