### ISSUE TITLE
Need workaround for bugs in Eclipse JDT

### ISSUE THREAD

**Issue by facboy** [xebia-france/selma#105]
There is a bug in the Eclipse JDT where it Types.asMemberOf does not work properly with methods on interfaces or superinterfaces:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=382590
https://bugs.eclipse.org/bugs/show_bug.cgi?id=481555

**Comment by slemesle** [comment]
I really don't see how to get a workaround for this.

**Comment by slemesle** [comment]
I've seen this in mapstruct that could help.
https://github.com/mapstruct/mapstruct/issues/644

**Comment by facboy** [comment]
yes i saw that too but wasn't sure whether to mention it :)

**Comment by slemesle** [comment]
The thing is I use intellij Idea so Eclipse JDT is not my business. 
Do you have one ? I'm pretty sure we can backport this patch to Selma. 

We can talk about mapstruct I already know Gunar so does he. 
Moreover, there are some inspiring features in mapstruct.

**Comment by facboy** [comment]
I use Intellij too, but some of our team use Eclipse.  Eclipse JDT is a major pain to work with.

**Comment by slemesle** [comment]
Good news https://bugs.eclipse.org/bugs/show_bug.cgi?id=481555 is fixed in eclipse.

I close this bug since eclipse will now support this.
