### ISSUE TITLE
It's impossible to use abstract class like a custom mapper

### ISSUE THREAD

**Issue by lifeinzik** [xebia-france/selma#108]
When a mapper use a custom mapper, the custom mapper constructor is call in the mapper constructor. If custom mapper is in an abstract class there is an error because  it's impossible to instantiate an abstract class. 

Is there any issue ? 

Thanks for V0.15

**Comment by slemesle** [comment]
In fact if the mapper itself is an abstract class, it will be used as a custom mapper for non abstract methods. 
So there is not much to do to allow the use of an abstract custom mapper.

**Comment by slemesle** [comment]
That does work now.

**Comment by lifeinzik** [comment]
Thank you for your quick reply :)
