### ISSUE TITLE
Not able to convert between Map<String, ?> and bean

### ISSUE THREAD

**Issue by james-hu** [xebia-france/selma#112]
I've tried to define conversion between bean and Map<String, ?>, but it seems this is not supported?

There are two use cases, one is to use a Map to hold properties of a bean, the other one is to retrieve properties from a Map in order to instantiate a bean.

**Comment by slemesle** [comment]
This can not be handled at compile time, if you really need something like that, then you should implement it on your own.

**Comment by james-hu** [comment]
What about do an if-else when generating the code? If the target or source type is Map<String, ?>, just generate corresponding code to handle that, otherwise, apply current logic.

**Comment by slemesle** [comment]
This will be something like re-inventing the wheel, you can create a custom mapper using another tool to implement this logic.
