### ISSUE TITLE
have an all-in-one jar for IntelliJ to pick up

### ISSUE THREAD

**Issue by james-hu** [xebia-france/selma#114]
In IntelliJ's "Preferences" -> "Build, Execution, Deployment" -> "Compiler" -> "Annotation Processors" -> "Processor path" , only one jar file can be specified, but Selma's processor requires two separate jar files (selma-processor and selma). It would be good if there can be an all-in-one jar file just for this use case.

**Comment by slemesle** [comment]
Hi sorry for replying so lately, you only have to select the radio button "obtain processors from project class path".

**Comment by slemesle** [comment]
The thing is that the processor code has nothing to do in production classes, this is why we split it in two jars.

**Comment by james-hu** [comment]
Doesn't "obtain processors from project class path" require selma-processor to be part of the project dependencies? However selma-processor jar should be considered as a compile time tool, rather than a runtime dependency.

**Comment by slemesle** [comment]
I am really sorry but I use IntelliJ with Selma for years and have never met this kind of issue. 
Both API and processor are dependencies at build time but the processor is not needed at runtime. 
So you are right selma-processor is a compile time tool. 
I personnaly use maven in IntelliJ with selma-processor as build time only and the radio button works well.
