### ISSUE TITLE
List index in source

### ISSUE THREAD

**Issue by mrCosmofen** [xebia-france/selma#117]
Hello!
I have an issue - I need to map from list to a single object
class Source {
List<String> names;
}
class Destination {
String name;
}
result must be something like this:

Destination map(Source src){
Destinatioin dst = new Destination()'
dst.setName(src.getNames().get(0));
return dest;
}

**Comment by slemesle** [comment]
Hi, 
I see two solutions for this :

1. Define a custom mapper for String to List that will contain the code of the map function you described above. 
2. In current snapshot, you do exactly the same and specify that this custom mapper should only apply on Source.names to Destination.name using the new custom field to field mapping.

**Comment by akoidan** [comment]
Maybe we can consider adding something like `@Field({"names[0]", "name"})`. The feature can be quite useful.
