### ISSUE TITLE
Mapping primitive long to String

### ISSUE THREAD

**Issue by pomverte** [xebia-france/selma#127]
Hello,

I've encounter un bug about a primitive type conversion long to String, the generated class doesn't compile.

The full example is here : https://github.com/pomverte/selma-convert-primitive

Cheers !

**Comment by vtomilin** [comment]
Not just long, I have a similar issue with int -> String

**Comment by slemesle** [comment]
Hi the primitive to String is now fixed there was a missing '+' in the generated code.
Sorry for this bug.

**Comment by vtomilin** [comment]
Thank you, @slemesle!

**Comment by slemesle** [comment]
Your welcome
