### ISSUE TITLE
source and destination have same List<Attachement> attachments, not working

### ISSUE THREAD

**Issue by jchen9shc** [xebia-france/selma#128]
I have a mapper like this:
@Mapper(withIgnoreMissing = IgnoreMissing.ALL, withCollectionStrategy = SETTER_ONLY)
public interface  BaseBeanMapper {
    NotificationContent asNotificationContent(EmailMessage emailMessage);
}

Both NotificationContent and EmailMessage have "List<Attachement> attachments", I tried all collectionStategy: GETTER_ONLY, Default, SETTER_ONLY, but always getting error:

Error:(15, 25) java: Failed to generate mapping method for type Email.Attachment to 
Email.Attachment to Email.Attachment not supported on util.BaseBeanMapper.asNotificationContent(beans.Email.EmailMessage) !
  --> Add a custom mapper or 'withIgnoreFields' on @Mapper or @Maps to fix this ! If you think this a Bug in Selma please report issue here [https://github.com/xebia-france/selma/issues].

Any info would be greatly appreciated.

Thanks,
Joe

**Comment by jchen9shc** [comment]
Actually it is Lombok and Selma issue, Selma processes it before Lombok generates getter/setter. Anyway go around this?

**Comment by slemesle** [comment]
Sadly, Selma is not able to work in the same source tree with lombok. 
You can only separate your code in different modules so the compiler can first process lombok and then compile the mappers with Selma.
