### ISSUE TITLE
Mapping to sub class property

### ISSUE THREAD

**Issue by pierre03** [xebia-france/selma#131]
Hello, i have a question about how to use selma to map the class from Person to ReceiverDto, because the class "Address" is not abstract, i have a web service SOAP which sends firstName and lastName to the server, how can i map this object Person, please? I have tried the selma, but i didn't find the solution.
Thank you.

public class Person {
	private String firstName;
	private String lastName;
	private String birthDate;
	private String address;
	private String city;
	//GETTER & SETTER...
}

public class ReceiverDto {
	private Date birthDate;
	private **Address** addressInfo;
	//GETTER & SETTER...
}

class **Address**{
	String address;
	String city;
}
class **IndividualAddress** extends Address{
	String firstName;
	String lastName;
	Type type = Type.INDIVIDUAL;
}

class CompanyAddress extends Address{
	String companyName; 
	Type type = Type.COMPANY;
}

enum Type{
	INDIVIDUAL,
	COMPANY;
}

**Comment by slemesle** [comment]
Simple response is you can not for now. 
The only way to know it is an IndividualAddress or a CompanyAddress is at runtime.
In that case I would write a custom interceptor for ReceiverDto to Person, ignore the address field and inside the interceptor use `instanceof`  to call another mapper (IndividualAddress to Person / CompanyAddress to Person).

So it would look like : 
```
@Mapper(withIgnoreFields="type")
abstract class DtoMapper {

  @Maps(withIgnoreFields="address")
  abstract Person mapDtoToPerson(ReceiverDto dto);

  abstract Person mapIndividualAddress(IndividualAddress in, Person out);

  abstract Person mapCompanyAddress(CompanyAddress in, Person out);

  public interceptPersonToDto(ReceiverDto dto, Person out){
     if (dto.address !=null){
           if (dto.address instanceof IndividualAddress) {
               this.mapIndividualAddress((IndividualAddress)dto.address, out);
           } else if (dto.address instanceof CompanyAddress) {
               this.mapCompanyAddress((CompanyAddress)dto.address, out);
          }
     }
  }

}
```
