### ISSUE TITLE
Conversion b/w Set and List of same/mapped object types

### ISSUE THREAD

**Issue by pkalwar** [xebia-france/selma#135]
Hi,

The generated code is complaining about conversion between a Set and List of same object type. I suggest it should be supported OOTB.

I also tried to define 2 methods to convert, with generic types (since its just a conversion of collection type, not contents), but Selma is not able to pickup those methods and still complains.

Am i doing anything wrong?
Thanks.

**Comment by pkalwar** [comment]
Also, to convert b/w Set and List of mapped objects (conversion methods have been provided to map/convert individual objects), still its asking for methods to convert Set/Lists of those objects again!!

for ex:

Class A{
  Set set1;        // note the Set here doesn't indicate the type of objects its holding, but are of type 'C'.
}

Class B {
  List<D> list1;
}

mapper method in an interface:

D c2d(C in, D out);
and vice-verse.

with mapping fields definition:   @Field({"B.list1","A.set1"})

Type of 'set1' in class A can't be indicated as its generated by another library.

Selma is now asking all combinations of methods to properly convert A to/from B in above scenario.
Please suggest, what is recommended here.

Thanks.

**Comment by slemesle** [comment]
Hi,

the thing here again is that Lists and Sets do not share the same contract and you can loose passing from one to another. So I think this kind of conversion should be decided by the dev and not simply automate but that can be subject to discussion. 

Now, please note that Selma is statically typed mapping which means it can not infer type at runtime. So for a custom mapper to work you should specify it's complete exact type signature. 

So you can specify a custom mapper : 

```
public Set mapListToSet (List in) { 
// ... 
}
```

and inside this one infer the generic type of the contained objects to call the mapping method. This can be easily done in an abstract class mapper. 

I am not sure this answer to your question, if not, can you give a real sample code ?

**Comment by pkalwar** [comment]
Sorry, didn't see this in time. I did use custom mappers only.
Thank you.
