### ISSUE TITLE
Redundant prefix in generated class name. 

### ISSUE THREAD

**Issue by artsiom-kotau** [xebia-france/selma#136]
I created the following mapper interface:
`@Mapper(
        withCustomFields = {
                @Field({"langId", "lang.id"}),
                @Field({"reference", "ref"})
        }
)
public interface CompanyMapper extends BeanMapper<Company, CompanyEntity> {
}`

where BeanMapper is:
`
public interface BeanMapper<D, E> {

    E mapToEntity(D dto);

    D mapToDto(E entity);
}
`

Also I have the following plugin configuration in pom:
`
                <plugin>
                    <groupId>org.bsc.maven</groupId>
                    <artifactId>maven-processor-plugin</artifactId>
                    <version>2.2.4</version>
                    <configuration>
                        <defaultOutputDirectory>
                            ${project.build.directory}/generated-sources/selma
                        </defaultOutputDirectory>
                        <processors>
                            <processor>fr.xebia.extras.selma.codegen.MapperProcessor</processor>
                        </processors>
                    </configuration>
                    <executions>
                        <execution>
                            <id>process</id>
                            <phase>generate-sources</phase>
                            <goals>
                                <goal>process</goal>
                            </goals>
                        </execution>
                    </executions>
                    <dependencies>
                        <dependency>
                            <groupId>fr.xebia.extras</groupId>
                            <artifactId>selma-processor</artifactId>
                            <version>0.15</version>
                        </dependency>
                    </dependencies>
                </plugin>

                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>1.9.1</version>
                    <executions>
                        <execution>
                            <id>add-source</id>
                            <phase>generate-sources</phase>
                            <goals>
                                <goal>add-source</goal>
                            </goals>
                            <configuration>
                                <sources>
                                    <source>${project.build.directory}/generated-sources/selma</source>
                                </sources>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <configuration>
                        <skip>true</skip>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.6.0</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-war-plugin</artifactId>
                    <version>3.0.0</version>
                    <configuration>
                        <failOnMissingWebXml>false</failOnMissingWebXml>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.mortbay.jetty</groupId>
                    <artifactId>jetty-maven-plugin</artifactId>
                    <version>8.1.16.v20140903</version>
                    <configuration>
                        <webApp>
                            <contextPath>/</contextPath>
                        </webApp>
                        <connectors>
                            <connector implementation="org.eclipse.jetty.server.nio.SelectChannelConnector">
                                <port>8080</port>
                            </connector>
                        </connectors>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.17</version>
                    <configuration>
                        <argLine>-Xmx512m</argLine>
                    </configuration>
                </plugin>
`

But generated classes has weird name in java file:
`public final class by.truckdock.service.company.CompanyMapperSelmaGeneratedClass
    implements y.CompanyMapper {
` 
How can I avoid this issue ?

P.S: sorry for incorrect marking in issue description

**Comment by slemesle** [comment]
Hi,

ok this one is weird :p. I've made some improvements on this code in SNAPSHOT. 
Can you give it a test ? 

Normally the generated classes should look like : 

```
package by.truckdock.service.company;

public final class CompanyMapperSelmaGeneratedClass implements CompanyMapper { 

// ...
```


If the snapshot build does not solve this issue, can you give me a complete sample code to reproduce it easily ?

Thanks

**Comment by slemesle** [comment]
Thanks for testing against SNAPSHOT version. 
So you need a new release available on maven central ?

**Comment by artsiom-kotau** [comment]
If it is possible to make release till the end of January, it would be wonderful )
