### ISSUE TITLE
New Feature: Implement withIoC={CDI, CDI_SINGLETON} options

### ISSUE THREAD

**Issue by Musikolo** [xebia-france/selma#137]
Hi,

I think it would be very useful to have support for Java CDI standard injection mechanism based on ``javax.inject.Inject`` annotation. Additionally, it would be great to have the ability to create singletons based on ``javax.inject.Singleton`` annotation too. My proposal is to incorporate to the Selma's ``@Mapper`` annotation the follow options for the existing ``withIoC`` attribute :
-  ``CDI``: This would add the ``javax.inject.Named`` annotation to the generated mapper class.
-  ``CDI_SINGLETON``: This would add the ``javax.inject.Named`` and ``javax.inject.Singleton`` annotations to the generated mapper class.

The result would be that later on that we would be able to do the following in our code:
```java
@Inject
private final UserMapper userMapper;
```

I've found [this implementation](https://github.com/xebia-france/selma/commit/009cc90df48d01c472de584fbf90002ed72dfaf1) to incorporate CDI to Selma, but I don't think it's compatible with the aforementioned request.

Thank you!

**Comment by slemesle** [comment]
Hi,

this is possible you can simply modify the implementation found to do it and add the support for `withIoCServiceName` parameter inside the code for CDI support. 

I would be pleased to merge such a pull request with the corresponding tests.

**Comment by slemesle** [comment]
may I close this issue now ?

**Comment by Musikolo** [comment]
Yes, I think so. I'll take care of it! :-)
