### ISSUE TITLE
Generate method to map Collection of object directly

### ISSUE THREAD

**Issue by TehBakker** [xebia-france/selma#142]
This is not a bug,  but a feature request (Didn't find where to add correct label)
Not talking about collection attribut but collection of object.

```
@Mapper
public interface MyMapper {
	// Handle this kind of method
	List<MyDto> convertToListMyDto(Set<MyEntity> source);

	MyDto convertToMyDto(MyEntity source);
}
```

To convert from my Set of source, Selma would just loop and call the singular convert method convertToMyDto. 
Would save a bit of code on the service side, not having to instanciate the collection; loop, and call convert for each item, then adding them to the result list.

Not a big deal, but i'd be nice and not very hard to implement I think ?

**Comment by slemesle** [comment]
Hi, 

Thanks for your request, there is no bigdeal with implementing Set to List in Selma. 
But, you may have surprising results since a Set does not share the same contract with a List. 
Some elements may disappear in the resulting Set. My first thought, is that the selma user should be aware of this leaky conversion thats why its not natively supported in Selma for now.

**Comment by TehBakker** [comment]
Hey, 

Thanks for the quick reply.
What about Set to Set or List to List ?

**Comment by slemesle** [comment]
Set to Set and List to List are well supported. 
Sorry my bad both should be well supported, if you have an issue with this kind of conversion it should be a bug.

The Selma collection mapping is the same applied if both in and out bean are Collection.

**Comment by TehBakker** [comment]
Ahhh, no it's my bad, I must have misunderstood the documentation : http://www.selma-java.org/#mapping-collections

I thought this only applied for list ATTRIBUTS of the object we want to map.

So would this code work as it is ? Confused as how I would apply  http://www.selma-java.org/#mapping-collections to my use case.

```
@Mapper
public interface MyMapper {
	// Handle this kind of method
	List<MyDto> convertToListMyDto(List<MyEntity> source);

	MyDto convertToMyDto(MyEntity source);
}
```

**Comment by slemesle** [comment]
Yes definitely it should work, and you don't even need the `convertToMyDto` method except if you need to give some specific configuration.
We should perhaps enhance the documentation to clarify this. 
See [https://github.com/xebia-france/selma/blob/master/processor/src/test/java/fr/xebia/extras/selma/it/mappers/CollectionsMapper.java] it uses Strings but it can also be Beans inside the collections.

If you have an idea to enhance the documentation about this, please tell me.

**Comment by TehBakker** [comment]
Perfect, sorry for hassle.
Maybe add that short exemple in the collection paragraph to show it's that simple for list object, just before list attributs ?
