### ISSUE TITLE
Mapping field from parent class failed

### ISSUE THREAD

**Issue by nbouad** [xebia-france/selma#144]
Hello Seven,

I have this issue with Selma :

_The destination:_

```
public class Destination {
    private String id;
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }
}
```

_The source:_

```
public class  Source extends AbstractSource {
}
```

with:
```
public class AbstractSource {
    private String id;
    public AbstractSource() {
    }
    public String getId() {
        return this.id;
    }
    public void setId(String id) {
        this.id = id;
    }
}
```

Selma generates this strange code:
  ```
/**
   * Mapping method overridden by Selma
   */
  @Override
  public final Destination asAddress(Source in) {
    Destination out = null;
    if (in != null) {
      out = new Destination();
      out.setId(asString(in.getId()));
    }
    return out;
  }

```
```
  /**
   * Mapping method overridden by Selma
   */
  public final String asString(Object in) {
    java.lang.String out = null;
    if (in != null) {
      out = new java.lang.String();
    }
    return out;
  }
```

The id is never mapped. Selma instantiate a default String without the source value is that normal?
Do I missed something ?

Najet

**Comment by slemesle** [comment]
Hello Najet,

sorry but can you provide the mapper code by itself ?

**Comment by nbouad** [comment]
Hi Seven !

My mapper :

`@Maps( withCustomFields = {
            @Field({"email", "adresse"})},
            withIgnoreFields = {"npai", "type", "updateDate"}
    )
    MailDto asMailDto(Mail mail);`

The Mail class inherit of a super class Coordinate containing the id.

The mapper generated by Selma is :

` /**
   * Mapping method overridden by Selma
   */
  @Override
  public final MailDto asMailDto(Mail in) {
    MailDto out = null;
    if (in != null) {
      out = new MailDto();
      out.setEmail(in.getAdresse());
      out.setId(asString(in.getId()));
    }
    return out;
  }

 /**
   * Mapping method overridden by Selma
   */
  public final String asString(Object in) {
    java.lang.String out = null;
    if (in != null) {
      out = new java.lang.String();
    }
    return out;
  }`

In the asString method, it seems something miss, does it ?

Thank you for your answer :)

**Comment by nbouad** [comment]
`  public class Mail extends AbstractCoordonnee {
        
        private String adresse;

        public Mail() {
        }

        public String getAdresse() {
            return this.adresse;
        }

        public void setAdresse(String adresse) {
            this.adresse = adresse;
        }
    }`

`public class MailDto {
   
    private String id;
    private String email;

    public MailDto() {
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}`

**Comment by slemesle** [comment]
Hi,
I added a test to reproduce this bug based on your code sample. The thing is I am not able to reproduce it, except if using an old version of Selma before 0.15. Can you update to Selma 1.0 ?
And inspect the test, I pushed for this issue, enrich it to reproduce the issue and make a pull request ?
