### ISSUE TITLE
Issue with mapping 'enum' to 'String' 

### ISSUE THREAD

**Issue by darklynx** [xebia-france/selma#153]
I'm not sure whether it is an issue or a feature (expected behavior). I'm trying to map data from one object to another where a property of source class is of `enum` type where as destination property is a `String`.

```Java
// source class
class Entity {
	enum Status { ACTIVE, FAILED, PENDING }
	private Integer code;
	private String description;
	private Status status;
	// + getters / setters
}

// destination class
class SimpleEntity {
	private String numericCode;
	private String text;
	private String statusCode;
	// + getters / setters
}

// mapping spec
@Mapper
interface EntityMapper {
	@Maps(withCustomFields = {
		@Field({ "code", "numericCode" }),
		@Field({ "description", "text" }),
		@Field({ "status", "statusCode" })
	}, withIgnoreMissing = IgnoreMissing.DESTINATION)
	SimpleEntity toSimpleEntity(Entity entity);
}

// unit test
class MappingTest {
	@Test
	void mapping() {
		Entity entity = new Entity();
		entity.setCode(5);
		entity.setDescription("active entity");
		entity.setStatus(Status.ACTIVE);

		EntityMapper mapper = Selma.getMapper(EntityMapper.class);
		SimpleEntity result = mapper.toSimpleEntity(entity);

		assertEquals(result.getNumericCode(), "5");
		assertEquals(result.getText(), "active entity");
		assertEquals(result.getStatusCode(), "ACTIVE");
	}
}
```

The execution of unit test fails:
```
...
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.268 sec <<< FAILURE! - in test.MappingTest
mapping(test.MappingTest)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError: expected [ACTIVE] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at test.MappingTest.mapping(MappingTest.java:26)
...
```

I also noticed that code generated by processor for mapping has an interesting implementation of `enum` -> `String`:
```Java
  public final String asString(Entity.Status inStatus) {
    java.lang.String out = null;
    if (inStatus != null) {
      out = new java.lang.String();
    }
    return out;
  }
```

why that? why not something like:
```Java
...
    if (inStatus != null) {
      out = String.valueOf(inStatus);
    }
...
```
or simply use `toString()` or `name()` method of `enum`? Is there any hidden meaning of current implementation?

Also `out.setNumericCode(inEntity.getCode() + "");` implementation for `Integer` looks incorrect to me, this would be fine for primitive `int`, but `null` value of `Integer` should be converted to `null` but not a `"null"`

**Comment by slemesle** [comment]
Hi @darklynx,

this definitely looks like a bug in Selma. I should have a look on this. 
But, I am not sure wether we should use toString enum method or name :p. 
For the Integer note, the code is surrounded with a null check if on the inEntity so  you won't find a null value.

**Comment by darklynx** [comment]
Hi,

For `enum` would suggest to use `.name()` at least by default (in case if you plan some more advanced mapping options in the future), because `enum` method `.valueOf(String name)` (implemented in java.lang.Enum<E> class) that does a reverse transformation from `String -> enum` uses the name of `enum` generated by `.name()` method rather than `toString()`

Also `.toString()` method of `enum` can be and sometimes is redefined by developer, whereas `.name()` is final and in a way more consistent in its uniqueness: there can be only one enum entry with the same `name` in the enumeration of a type, but, if redefined, there can be several enum entries generating the same result when `toString()` is called.

Regarding the `Integer`, I was also surprised, because there were no null-check surrounding the code, I pretty certain of that, because I even tested it with unit test and got a message null is not equal null, which is in TestNG a bit ambiguous but means that null object is not equals "null" string.

However, I can regenerate what Selma compiler has produced and post here.

**Comment by darklynx** [comment]
Generated code:

```Java
// GENERATED BY S3LM4
package demo;


public final class EntityMapperSelmaGeneratedClass
    implements EntityMapper {

  @Override
  public final SimpleEntity toSimpleEntity(Entity inEntity) {
    demo.SimpleEntity out = null;
    if (inEntity != null) {
      out = new demo.SimpleEntity();
      out.setNumericCode(inEntity.getCode() + "");
      out.setText(inEntity.getDescription());
      out.setStatusCode(asString(inEntity.getStatus()));
    }
    return out;
  }

  public final String asString(Entity.Status inStatus) {
    java.lang.String out = null;
    if (inStatus != null) {
      out = new java.lang.String();
    }
    return out;
  }



  /**
   * Single constructor
   */
  public EntityMapperSelmaGeneratedClass() {
  }

}
```

And corresponding unit test:
```Java
...
	@Test
	void nullMapping() {
		Entity entity = new Entity();
		entity.setCode(null);

		EntityMapper mapper = Selma.getMapper(EntityMapper.class);
		SimpleEntity result = mapper.toSimpleEntity(entity);

		assertNull(result.getNumericCode());
	}
...
```

Results into following error message:
```
nullMapping(demo.MappingTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: expected [null] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotSame(Assert.java:509)
	at org.testng.Assert.assertNull(Assert.java:445)
	at org.testng.Assert.assertNull(Assert.java:434)
	at demo.MappingTest.nullMapping(MappingTest.java:50)


Results :

Failed tests:
  MappingTest.mapping:38 expected [ACTIVE] but found []
  MappingTest.nullMapping:50 expected [null] but found [null]

...
```

**Comment by darklynx** [comment]
Selma version: `1.0` for both `selma-processor` and `selma`
JavaWriter version: `2.5.0` (the only dependency of selma processor)
Java version: 1.8

I use maven, but I do not think it has anything to do with that :)

**Comment by slemesle** [comment]
That should work by calling toString() on the enum.
Can you give it a try in nightly builds ?
