### ISSUE TITLE
Collections mapping under SpringBoot 2.0

### ISSUE THREAD

**Issue by surdsey** [xebia-france/selma#154]
Hi,
In a quite simple case, using onetomany <-> manytoone link between two beens, i did'nt found any way to make system populate the OneToMany reverse map. Using SpringBoot 2.0, Selma 1.0, hibernate 5.2.10 and PostgreSQL, Lombok generating getters and setters, a call to the generated getter for the onetomany field always return a null pointer.
In other case, using repository to retrieve a user fails to map the onetomany link with that error:
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role.

Here come a part of the code for tests:

Child:
@Entity
@Table(name = "Cards")
@Data
@Builder
public class Card {
...
  @ManyToOne(cascade = {CascadeType.DETACH, CascadeType.MERGE,
      CascadeType.PERSIST, CascadeType.REFRESH},
      fetch = FetchType.LAZY)
  private User consumedByUser;
}

Parent:
@Entity
@Table(name = "Users")
@Data
@Builder
public class User {
...
  @OneToMany(mappedBy = "consumedByUser", cascade = {CascadeType.DETACH,
      CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH},
      fetch = FetchType.LAZY)
  private Collection<Card> cardConsumedByUserLinks;
}

The test:
@Test
  public void testUserLoading() {
    final String userFirstName = "test first name";
    final String userLastName = "test last name";
    UserDto userDto = UserDto.builder().firstName(userFirstName)
        .lastName(userLastName)
        .build();

    User userStored = userRepository.save(mapper.asUser(userDto));
    CardDto cardDto = CardDto.builder()
        .consumedByUser(userDto)
        .build();
    Card card = cardRepository.save(mapper.asCard(cardDto));
    Assert.assertNotNull(card);

    Optional<User> userLoadOpt = userRepository
        .findUserById(userStored.getId());
    Assert.assertNotNull(userLoadOpt.get());
    // Error 1: lazy failure
    userDto = mapper.asUserDto(userLoadOpt.get());

    Optional<User> cons = userRepository.findUserAsCardConsumer(card);
    Assert.assertNotNull(cons.get());

    // Error 2: without reloading user from DataBase, the next test fails with enpty map
    // whereas a SQL request successfully retrieve the link between objects.
    Assert.assertNotNull(userDto.getCardConsumedByUserLinks());
  }

As mentionned, 
Thanks for help in advance
Nicolas from Wedoogift

**Comment by slemesle** [comment]
Any update on this issue ?

**Comment by surdsey** [comment]
Hello,
Sorry to be late. The onetomany problems mainly come from hibernate/lombok. While lombok generates a toString method which reference entity methods which try to retrieve information from database. In comparable cases selma generates a class which uses methods like collection.size() or collection.isEmpty() and out of db session, it will fail in hibernate context with a proxy exception.
I don't think there is a solution since collections methods automatically access database instead of local values.
Thank you for your attention.
