### ISSUE TITLE
Mapper IoC.SPRING and custom mapper

### ISSUE THREAD

**Issue by surdsey** [xebia-france/selma#157]
Hello,
In the specific case of Mapper declared "withIoC = IoC.SPRING" and with a custom mapper for Money conversion in a SpringBoot project, I got a problem about Spring Autowiring beans:

No qualifying bean of type 'com.***.converter.mapper.MoneyToMoneyCustomMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

In fact I don't know if there is is a solution but it seems obvious that Spring tries converting a native object into bean whereas the Selma documentation doesn't specify modifications for this use case.

Any idea ?
Thanks in advance

**Comment by slemesle** [comment]
In this case, the MoneyToMoneyCustomMapper should be available for Spring. 
So you should annotate it with a @Service or add it to your Spring config bean so IoC can work. 

Selma does not try to explain the use of Spring for sure. We just explain that you can use Spring to build the mapper and link it with its dependencies. All dependencies should be managed by Spring in this case. 

I hope this helps.

**Comment by surdsey** [comment]
Thank you for your quick answer.
I knew that the custom mapper had to be "serviced" but I thought perhaps you had the same issue with a best adaptation not to consider a mapper as a service. Anyway, it works.

**Comment by slemesle** [comment]
Good to hear that it works.
Sorry but I do not have a better solution. What is disturbing you in considering the mapper as a service ?

**Comment by slemesle** [comment]
Any update about the use of the mapper as a service ?

**Comment by surdsey** [comment]
Sorry for the late answering. The problem only was to turn a classic class into a bean only for that use but finally it remains the easier solution so we adopted that and everything' fine now.
Thank you
