### ISSUE TITLE
Collection strategy ALLOW_GETTER only appends

### ISSUE THREAD

**Issue by reitzmichnicht** [xebia-france/selma#159]
Hi

Use Case: 
Mapping from Entity to Dto with OneToMany collection.
The Dto is created successfully with the collection entries.
The Dto is now modified and one collection entry is removed.
Mapping back from Dto to Entity will read the existing entity collection and try to add the remaining entries from the dto collection.

So with ALLOW_GETTER there is a clear missing before the mapping starts, otherwise it will only append.

Kind regards,
Michael

**Comment by slemesle** [comment]
I added a clear before adding mapped elements from the source. 

Thanks for the report.

**Comment by reitzmichnicht** [comment]
thank you for the fast fix
