### ISSUE TITLE
Mapping primitive with withIgnoreNullValue = true does not compile

### ISSUE THREAD

**Issue by larcaini** [xebia-france/selma#186]
When input object have primitive attribute (long for example) and the mapper interface use the "withIgnoreNullValue = true" parameter, the generated code fail to compile. It generates the following code :

```
if (inObject.getId() != null) {
  out.setId(inObject.getId() + "");
}
```

And corresponding error message, which is right :
`Error:(XX, XX) java: incomparable types: long and <nulltype>`

Removing the null check for primitives looks like an obvious fix. Hope it's easy to do.

**Comment by slemesle** [comment]
Can you give it a test in snapshot builds ?

**Comment by larcaini** [comment]
Hi, sorry for the delay !
I just checked it with last 1.1-SNAPSHOT and it works as expected.
Keep up the good work.
