### ISSUE TITLE
Cyclic mapping defense

### ISSUE THREAD

**Issue by slemesle** [xebia-france/selma#2]
Selma should either forbid cyclic mapping by failing at compile time or 
have a smarter way. 

Selma should never go in eternal mapping loop in such condition.

Bean A contains a bean B which contains original A.

**Comment by jandsu** [comment]
I had solved this in a former homegrown solution.
If this can help, what I ended up with was a cache:
[target class + source reference => target reference]
which I had implemented using:
HashMap<Class<TARGET>, HashMap<SRC, TARGET>>

The rationale for the target class was that the same "source" could be mapped twice in the DTO tree. The reason for not using an IdentityHashMap was that our underlying lib above JPA would possibly generate several instances for the same row in the database...

The cache only lived inside a top level conversion from the user... (it was cleared as soon as the conversion returned to the user). In other words, if I had a Person with an Address (both translating to PersonDto and AddressDto) the cached would last from the Person to PersonDto conversion (including the nested Address to AddressDto). However, if the user explicitly asked to translate an Address to an AddressDto (not as part of a Person), then the cache would last just there...
It was therefore stored inside a ThreadLocal.

This allowed to convert complex structures such as graphs.
