### ISSUE TITLE
Null value management

### ISSUE THREAD

**Issue by barmic** [xebia-france/selma#52]
It could be intersting to management the null value.
For exemple if I want map a collection between 2 bean and I want that if the source collection is null, I create an empty collection in destination.

Currently, I use a workarround in setter to make that :

```
public void setMyList(List myList) {
    this.myList = (null != myList) ? myList: Collections.emptyList();
}
```

I propose to add a field in Mapper annotation to allow null value in parameter of custom mapper methods.

**Comment by slemesle** [comment]
In fact, I think this is a bug since the custom mapper should be called even for null values.

**Comment by slemesle** [comment]
Fixed in snapshot build, you can check if that is good for you ?
