### ISSUE TITLE
Selma doesn't support defensive copy of lists

### ISSUE THREAD

**Issue by seblm** [xebia-france/selma#55]
Given a bean that defensively copy the list on setter i.e. it performs a copy of it
When using a selma mapper for destination.
Then values are not copied.

You can find a failing test on [this project](https://github.com/seblm/code-samples/tree/master/selma-defensive-copy).

**Comment by slemesle** [comment]
Ok I've adde an IT to confirm resolution. 
Please notice that defensive copy with Selma is useless, since Selma warrants defensive copy all mapped objects except immutables.
