### ISSUE TITLE
Documentation does not reflect current release

### ISSUE THREAD

**Issue by jpeffer** [xebia-france/selma#56]
It appears the documentation on the site does not currently reflect release version 0.12, which, based on the release notes, introduces new functionality and deprecates others. Updating the docs to reflect these changes would be extremely helpful and greatly appreciated!

**Comment by slemesle** [comment]
Hi the documentation update is planned. 

You can have a look to the closed issues to have a better idea of the released work. 
We got Spring IoC, Collection mapping from getter, few bug fixes. 
you could have a look here:
[https://github.com/xebia-france/selma/issues?q=milestone%3A0.11]

**Comment by jpeffer** [comment]
Is this project still being maintained or are development efforts being dropped? I understand life gets in the way sometimes, just trying to assess the health / future of Selma. Fantastic mapping library, really hope it continues to be supported.

I have seen people looking for the ability to define custom mappers at the @Field level, as well. Is there already a way to do this? Sometimes I need to define a custom mapper for a String to String, which only applies to a given field. Not having to create a custom mapper for the entire object would be nice.

**Comment by slemesle** [comment]
Hi, 
thanks for the "fantastic mapping library" word. I'll keep on working on the code, I just have some other time consuming projects  for the moment. 

I know that Selma needs a way to define a per-property custom mapping. You can log an issue for that and perhaps propose a way of doing it nicely. I am not sure the @Field level is the good one but it's an idea. 
Now that you look familiar to the library, for the documentation issue I would suggest to submit a pull request :). Help is appreciated, keeping the project alive remains a strong goal for me but having contributors is also a good point to keep the project on track.

Thanks for your comment, I hope to see you in near future here.
