### ISSUE TITLE
Generated class does not compile when denormalize field

### ISSUE THREAD

**Issue by BenoitCharret** [xebia-france/selma#66]
Hi,

When I try to map something like element.subList to list, the generated class, does not compile anymore.

a test case : https://github.com/BenoitCharret/selma-test/tree/case_2
The name of the variable is not well formed is this case : 
 if (in.getElement().getSubElementList() != null) {
          java.util.ArrayList<com.test.to.AnotherSubElement>    **ain.getElement().getSubElementList()TmpCollection** = new java.util.ArrayList<com.test.to.AnotherSubElement>(in.getElement().getSubElementList().size());
          out.setInfos(ain.getElement().getSubElementList()TmpCollection);
          for (com.test.from.SubSubElement ain.getElement().getSubElementList()Item : in.getElement().getSubElementList()) {
            ain.getElement().getSubElementList()TmpCollection.add(customMapperSubSubElementMapper.asAnotherSubElement(ain.getElement().getSubElementList()Item));
          }
        }

thanks for your help

**Comment by slemesle** [comment]
Hi,

can you confirm that the bug is fixed ?

**Comment by BenoitCharret** [comment]
Yes it fix the issue
