### ISSUE TITLE
Update mode does not apply to subSet

### ISSUE THREAD

**Issue by BenoitCharret** [xebia-france/selma#67]
Hi,
I want to map a bean in update mode. I define a Custom mapper for sublist (with an update mode too).
In that case, selma generate update mode for the wrong case.
Let see an example here : https://github.com/BenoitCharret/selma-test/tree/case_3

public class MySubMapper {

    public List<AnotherSubElement> anotherSubElements(String element){
        ...
    }

    public List<AnotherSubElement> anotherSubElements(String element,List<AnotherSubElement> elements){
        ....
    }
-------
@Mapper(
        withCustomFields = {
                @Field({"element", "infos"})
        },
        withCustom = {MySubMapper.class}
)

public interface MyMapper {

    ToA asA(FromA fromA);

    ToA asA(FromA fromA,ToA toA);

}

The generated code gives : 

public final com.test.to.ToA asA(com.test.from.FromA in) {
    com.test.to.ToA out = null;
    if (in != null) {
      out = new com.test.to.ToA();
      out.setInfos(customMapperMySubMapper.anotherSubElements(in.getElement(), out.getInfos()));

@Override
  public final com.test.to.ToA asA(com.test.from.FromA in, com.test.to.ToA out) {
    if (in != null) {
      if (out == null) {
        out = new com.test.to.ToA();
      }
      out.setInfos(customMapperMySubMapper.anotherSubElements(in.getElement()));

I thought that on the first case, the call should be  out.setInfos(customMapperMySubMapper.anotherSubElements(in.getElement())); 

and on the second (update mode) 
out.setInfos(customMapperMySubMapper.anotherSubElements(in.getElement(), out.getInfos()));

regards

**Comment by slemesle** [comment]
Got it there is a bug in hashcode from the TypeMirror class of JSR 269 :p. This was causing Selma not handling both custom mapping methods as the same Type pair. 

Snapshot build should now be fixed for this buggy behavior.

**Comment by BenoitCharret** [comment]
Hi,

the snapshot build solve the issue.

Thanks

**Comment by BenoitCharret** [comment]
Hi,

Can you made a release for the last fix ?

Regards
