### ISSUE TITLE
Generic field types not supported!

### ISSUE THREAD

**Issue by bhdrk** [xebia-france/selma#73]
I have a BaseEntity class.

```java
@MappedSuperclass
public abstract class BaseEntity<PK extends Serializable>  {

    @Id
    @GeneratedValue
    @Basic(optional = false)
    @Column(name = "id", nullable = false)
    private PK id;

    public PK getId() {
        return id;
    }

    public void setId(PK id) {
        this.id = id;
    }
}

```
and a JPA Entity class that extends BaseEntity

```java
@Entity
@Table(name="scenario")
public class Scenario extends BaseEntity<Long> {
}

```
and a DTO class

```java
public class ScenarioDTO {

    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
```

Mapper:

```java
@Mapper(withIgnoreMissing = IgnoreMissing.ALL)
public interface MyMapper {

    Scenario dto2Scenario(ScenarioDTO dto, Scenario scenario);
}

```

Destination is a JPA entity and  'id' field type is a generic type and its type is specified as java.lang.Long like DTO's id field. So I expected that it should work. But I got this error message

> error: Failed to generate mapping method for type java.lang.Long to PK not supported on MyMapper.dto2Scenario(demo.restapi.model.ScenarioDTO,demo.domain.Scenario) !

**Comment by slemesle** [comment]
This is fixed in snapshot build could you give it a try ?

**Comment by bhdrk** [comment]
Ok @slemesle, I will wait for the next release. Thanks...
