### ISSUE TITLE
Map multiplie fields into one

### ISSUE THREAD

**Issue by denouche** [xebia-france/selma#74]
Hi,

I have a problem and I cannot figure out how to use Selma to handle it.

My beans are the following:
```java
public class Destination {
  private Long id;
  private String lang;
  private String title;
  private Set<String> otherLabels;

  public Destination(String lang) {
    this.lang = lang;
  }
}
```

```java
public class Source {
  private Long id;
  private Set<Label> title;
  private Set<Label> otherLabels;
}
public class Label {
  private String lang;
  private String value;
}
```

I would like to be able to map the `source.labels` to `destination.label` according to the `destination.lang`, to finally call something like:
`mapper.updateDest(source, new Destination(lang))`

Same thing with `otherLabels` field.

The problem is that Selma does not allow (to my to knowledge) to map an attribute to another being aware of the whole bean, to access other attributes while mapping a field.

Maybe the answer is to be able to have a custom mapper like:
```java
  public String asString(Set<Label> in, Source source, Destination destination) {
    // If I have access here to destination and source I call handle my case and other cases which need to access to Sources properties to realize the mapping
  }
```
Maybe there is another easier answer to my question?

Thanks you in advance

**Comment by slemesle** [comment]
Hi,

for this kind of use, I would recommend handling the business logic on your own. 

You can use a mapper interceptor to have access to source and destination. 

```java
public class MapperInterceptor {
    public void interceptSourceToDestination(Source source, Destination destination) {
        // Do some processing here the destination is already mapped.
    }
}
```

The custom mapper is also a good point, but I definitely thinks this kind of mapping should be handled using Selma. This looks like business logic and not stupid mapping :p. 
If your beans are really those so it will take about 10 mins to implement the code needed by hand. 

Sorry but I don't see any help in Selma for that. I'll rethink about it but I do not have better idea than this one.
