### ISSUE TITLE
Joda LocalDate & LocalDateTime Support Not available

### ISSUE THREAD

**Issue by paraglohiya** [xebia-france/selma#87]
Hi,

Firstly let me thank you for coming up with this great utility.
Its fast and easy.
We use Joda LocalDate & LocalDateTime a lot could you please add support for the library in your project.

Thanks!
Parag

**Comment by slemesle** [comment]
Hi,

Selma already has builtin support for java.time (JSR-310). If you need joda  LocalDate & LocalDateTime support you can simply add those classes as immutable because they are.

```java

@Mapper( withImmutables = {LocalDate.class, LocalDateTime.class})
public interface JodaMapper {
 // ...
}
```

I think this will make the job.

**Comment by paraglohiya** [comment]
Thanks for quick reply let me try it

**Comment by slemesle** [comment]
Any update about this ?

**Comment by paraglohiya** [comment]
Hi,

It works like a charm. Thanks 

How do you copy a list of object to another list of objects

Person 
I'd
FirstName

List<person>

Employee
I'd
Name

List<Employee>

I already have a mapping for Person and Employee using Selma

Is there easy way to use the same

Currently I am using a for loop with exiting mapping

**Comment by slemesle** [comment]
For this kind you can : 

```
List<Person> asPersons(List<Employee> employees);
```
