### ISSUE TITLE
Selma raises mapping field error for static methods

### ISSUE THREAD

**Issue by facboy** [xebia-france/selma#89]
The mapping code seems to be picking up static methods on the bean class (eg getX, isY) and complaining that they are not mapped.  This seems like it should be a bug?

**Comment by slemesle** [comment]
yes it looks like a bug. We should definitely filter static methods in the BeanWrapper#buildFieldGraph() method.

**Comment by slemesle** [comment]
I've commited a fix for this, it should be available in nightly build shortly.

**Comment by facboy** [comment]
I'm not sure the fix is entirely right, maybe I'm thinking unclearly but won't it only exclude methods that are both static and abstract, not either/or?

**Comment by slemesle** [comment]
Good point for you @facboy thanks. 
This should be good now.

**Comment by facboy** [comment]
actually I missed this, why are we excluding abstract methods?  this breaks my code now as some of my source beans have abstract methods that are implemented in a sub-class (eg google autovalue)
