### ISSUE TITLE
Compile error: setter for XXX is missing from destination field if setter doesn't return void

### ISSUE THREAD

**Issue by bfg** [xebia-france/selma#94]
If destination bean setter is fluent (returns ```this``` for example) compile error is issued:

```java
    @Maps(
            withIgnoreFields = {"id"},
            withCustomFields = {
                    @Field({"DbModel.uniqueId", "DtoModel.profileId"}),
            }
    )
    DbModel updateFromDto(DtoModel dto, DbModel profile);
```

DbModel contains setter ```DbModel setUniqueId(String id)``` If i change setter return type to ```void ``` compilation succeeds.

**Comment by slemesle** [comment]
@facboy Thanks for the PR great work :)
