### ISSUE TITLE
Failed to generate mapping method

### ISSUE THREAD

**Issue by loutente** [xebia-france/selma#99]
Hi,

I've this compile error.
`
Error:(34, 18) java: Failed to generate mapping method for type com.test.Period to com.test.PeriodResource not supported on com.test.PeriodMapper.toResource(com.test.Period) !
  --> Add a custom mapper or 'withIgnoreFields' on @Mapper or @Maps to fix this ! If you think this a Bug in Selma please report issue here `[https://github.com/xebia-france/selma/issues].
`
I've attached the sample maven project.

[selma.zip](https://github.com/xebia-france/selma/files/341765/selma.zip)

**Comment by slemesle** [comment]
Hi,

did you try to add a default constructor to PeriodResource class ? I think this is what selma miss. The error message is not really helping and should be improved.

**Comment by loutente** [comment]
Hi,
That works thanks.

It will be fine, If you could update the documentation.

**Comment by gkirill** [comment]
Confirming this worked in my case too. Had some classes with custom constructors without an empty constructor and that was causing the same error.

**Comment by TheStijn** [comment]
Why not throw an error containing something like "can't map because no default constructor exists on ..."? I'm sure this would have saved a bunch of people some time :).

**Comment by Anshulrathi** [comment]
> Hi,
> 
> did you try to add a default constructor to PeriodResource class ? I think this is what selma miss. The error message is not really helping and should be improved.

Hi,
How can we deal the situation if we don't have default constructor available in class like I am trying to Map **StackTraceElement** Object but getting the same error like mentioned in original thread.

**error: Failed to generate mapping method for type java.lang.StackTraceElement to java.lang.StackTraceElement not supported on asObjectA(ObjectADTO) !
    public abstract ObjectA asObjectA(ObjectADTO objectADTO);
                                          ^
  --> Add a custom mapper or 'withIgnoreFields' on @Mapper or @Maps to fix this ! If you think this a Bug in Selma please report issue here [https://github.com/xebia-france/selma/issues].**
